question1: ex1_1.cpp
	g++ -o ex1_1.exe ex1_1.cpp -lgdi32
	./ex1_1.exe

question2: ex1_2.cpp
	g++ -o ex1_2.exe ex1_2.cpp -lgdi32
	./ex1_2.exe

question3 : ex1_3.cpp
	g++ -o ex1_3.exe ex1_3.cpp -lgdi32
	./ex1_3.exe

question4 : ex1_4.cpp
	g++ -o ex1_4.exe ex1_4.cpp -lgdi32
	./ex1_4.exe

question5 : ex1_5.cpp
	g++ -o ex1_5.exe ex1_5.cpp -lgdi32
	./ex1_5.exe

question6 : ex1_6.cpp
	g++ -o ex1_6.exe ex1_6.cpp -lgdi32
	./ex1_6.exe

test: test.cpp
	g++ -o test.exe test.cpp -lgdi32
	./test.exe
